name: Agendamento SMS a cada 2 minutos

on:
  schedule:
    - cron: '*/2 * * * *'  # A cada 2 minutos
  workflow_dispatch:

jobs:
  executar-processamento:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar API do Vercel
        run: |
           curl -X GET https://despachantebetodehon.vercel.app/api/processaAgendamentos \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"



