name: Cron de Agendamento SMS

on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos
  workflow_dispatch:        # Permite executar manualmente no GitHub

jobs:
  executar-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar API do Vercel para processar agendamentos
        run: |
          curl -X GET https://despachantebetodehon.vercel.app/api/processaAgendamentos \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
